# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import chat_pb2 as protos_dot_chat__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendPrivateMessage = channel.unary_unary(
                '/ChatServiceManager/SendPrivateMessage',
                request_serializer=protos_dot_chat__pb2.SendPrivateMessageRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.SendPrivateMessageResponse.FromString,
                _registered_method=True)
        self.GetPrivateChatHistory = channel.unary_unary(
                '/ChatServiceManager/GetPrivateChatHistory',
                request_serializer=protos_dot_chat__pb2.GetPrivateChatHistoryRequest.SerializeToString,
                response_deserializer=protos_dot_chat__pb2.GetPrivateChatHistoryResponse.FromString,
                _registered_method=True)


class ChatServiceManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendPrivateMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrivateChatHistory(self, request, context):
        """rpc SendRoomMessage (SendRoomMessageRequest) returns (SendRoomMessageResponse);
        rpc GetRoomHistory (GetRoomHistoryRequest) returns (GetRoomHistoryResponse);
        rpc CreateRoom (CreateRoomRequest) returns (CreateRoomResponse);
        rpc JoinRoom (JoinRoomRequest) returns (JoinRoomResponse);
        rpc LeaveRoom (LeaveRoomRequest) returns (LeaveRoomResponse);
        rpc AddUserToRoom (AddUserToRoomRequest) returns (AddUserToRoomResponse);
        rpc RemoveUserFromRoom (RemoveUserFromRoomRequest) returns (RemoveUserFromRoomResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendPrivateMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPrivateMessage,
                    request_deserializer=protos_dot_chat__pb2.SendPrivateMessageRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.SendPrivateMessageResponse.SerializeToString,
            ),
            'GetPrivateChatHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrivateChatHistory,
                    request_deserializer=protos_dot_chat__pb2.GetPrivateChatHistoryRequest.FromString,
                    response_serializer=protos_dot_chat__pb2.GetPrivateChatHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ChatServiceManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ChatServiceManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatServiceManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendPrivateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChatServiceManager/SendPrivateMessage',
            protos_dot_chat__pb2.SendPrivateMessageRequest.SerializeToString,
            protos_dot_chat__pb2.SendPrivateMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrivateChatHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ChatServiceManager/GetPrivateChatHistory',
            protos_dot_chat__pb2.GetPrivateChatHistoryRequest.SerializeToString,
            protos_dot_chat__pb2.GetPrivateChatHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
