version: '3.8'

services:
  service-discovery:
    build:
      context: ./src/ServiceDiscovery
    container_name: service-discovery
    ports:
      - "5003:5003"
    networks:
      - app-network
    env_file: ./src/ServiceDiscovery/.env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  user-service:
    build:
      context: ./src/UserService
    container_name: user-service
    ports:
      - "5002:5002"
      - "5007:5007"
    depends_on:
      - redis
      - service-discovery
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USER_CONNECTION_STRING=${USER_CONNECTION_STRING}
      - USER_DATABASE_NAME=${USER_DATABASE_NAME}
      - SERVICE_DISCOVERY_ADDRESS=${SERVICE_DISCOVERY_ADDRESS}
      - PORT=5002
      - SERVICE_NAME=user_service
      - JWT_SECRET=${JWT_SECRET}

  chat-service:
    build:
      context: ./src/ChatService
    container_name: chat-service
    ports:
      - "5001:5001"
      - "5008:5008"
    depends_on:
      - service-discovery
      - user-service
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CHAT_CONNECTION_STRING=${CHAT_CONNECTION_STRING}
      - CHAT_DATABASE_NAME=${CHAT_DATABASE_NAME}
      - SERVICE_DISCOVERY_ADDRESS=${SERVICE_DISCOVERY_ADDRESS}
      - PORT=5001
      - SERVICE_NAME=chat_service
      - USER_SERVICE_NAME=user_service

  gateway:
    build:
      context: ./src/Gateway
    container_name: gateway
    ports:
      - "5000:5000"
    depends_on:
      - service-discovery
      - user-service
      - chat-service
    networks:
      - app-network
    env_file: ./src/Gateway/.env

networks:
  app-network:
    driver: bridge
