version: '3.8'

services:
  service-discovery:
    build:
      context: ./src/ServiceDiscovery
    container_name: service-discovery
    ports:
      - "5003:5003"
    networks:
      - app-network
    env_file: ./src/ServiceDiscovery/.env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db

  user-service:
    build:
      context: ./src/UserService
    container_name: user-service
    ports:
      - "50022:50022"
      - "50077:50077"
    depends_on:
      - redis
      - service-discovery
      - mongodb
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USER_CONNECTION_STRING=${CONNECTION_STRING}
      - USER_DATABASE_NAME=${USER_DATABASE_NAME}
      - SERVICE_DISCOVERY_ADDRESS=${SERVICE_DISCOVERY_ADDRESS}
      - PORT=50022
      - SERVICE_NAME=user_service
      - JWT_SECRET=${JWT_SECRET}
      - GRPC_PORT=50022
      - WEBSOCKET_PORT=50077

  chat-service:
    build:
      context: ./src/ChatService
    container_name: chat-service
    ports:
      - "5001:5001"
      - "5008:5008"
    depends_on:
      - service-discovery
      - user-service
      - mongodb
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CHAT_CONNECTION_STRING=${CONNECTION_STRING}
      - CHAT_DATABASE_NAME=${CHAT_DATABASE_NAME}
      - SERVICE_DISCOVERY_ADDRESS=${SERVICE_DISCOVERY_ADDRESS}
      - PORT=5001
      - SERVICE_NAME=chat_service
      - USER_SERVICE_NAME=user_service

  gateway:
    build:
      context: ./src/Gateway
    container_name: gateway
    ports:
      - "5000:5000"
    depends_on:
      - service-discovery
      - user-service
      - chat-service
      - redis
      - mongodb
    networks:
      - app-network
    env_file: ./src/Gateway/.env

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data: