version: '3.8'

services:
  service-discovery:
    build:
      context: ./src/ServiceDiscovery
    container_name: service-discovery
    ports:
      - "5003:5003"
    networks:
      - app-network
    env_file: ./src/ServiceDiscovery/.env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db

  user-service:
    build:
      context: ./src/UserService
    container_name: user-service
    ports:
      - "50022:50022"
      - "50077:50077"
    depends_on:
      - redis
      - service-discovery
      - mongodb
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USER_CONNECTION_STRING=${CONNECTION_STRING}
      - USER_DATABASE_NAME=${USER_DATABASE_NAME}
      - SERVICE_DISCOVERY_ADDRESS=${SERVICE_DISCOVERY_ADDRESS}
      - SERVICE_URL=user-service:50022
      - SERVICE_NAME=user_service
      - JWT_SECRET=${JWT_SECRET}
      - GRPC_PORT=50022
      - WEBSOCKET_PORT=50077

  user-service2:
    build:
      context: ./src/UserService
    container_name: user-service2
    ports:
      - "50023:50023"
      - "50078:50078"
    depends_on:
      - redis
      - service-discovery
      - mongodb
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USER_CONNECTION_STRING=${CONNECTION_STRING}
      - USER_DATABASE_NAME=${USER_DATABASE_NAME}
      - SERVICE_DISCOVERY_ADDRESS=${SERVICE_DISCOVERY_ADDRESS}
      - SERVICE_URL=user-service2:50023
      - SERVICE_NAME=user_service
      - JWT_SECRET=${JWT_SECRET}
      - GRPC_PORT=50023
      - WEBSOCKET_PORT=50078

  # user-service3:
  #   build:
  #     context: ./src/UserService
  #   container_name: user-service3
  #   ports:
  #     - "50024:50024"
  #     - "50079:50079"
  #   depends_on:
  #     - redis
  #     - service-discovery
  #     - mongodb
  #   networks:
  #     - app-network
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - USER_CONNECTION_STRING=${CONNECTION_STRING}
  #     - USER_DATABASE_NAME=${USER_DATABASE_NAME}
  #     - SERVICE_DISCOVERY_ADDRESS=${SERVICE_DISCOVERY_ADDRESS}
  #     - PORT=50024
  #     - SERVICE_NAME=user_service
  #     - JWT_SECRET=${JWT_SECRET}
  #     - GRPC_PORT=50024
  #     - WEBSOCKET_PORT=50079

  chat-service:
    build:
      context: ./src/ChatService
    container_name: chat-service
    ports:
      - "50033:50033"
      - "50088:50088"
    depends_on:
      - service-discovery
      - user-service
      - mongodb
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CHAT_CONNECTION_STRING=${CONNECTION_STRING}
      - CHAT_DATABASE_NAME=${CHAT_DATABASE_NAME}
      - SERVICE_DISCOVERY_ADDRESS=${SERVICE_DISCOVERY_ADDRESS}
      - SERVICE_URL=chat-service:50033
      - SERVICE_NAME=chat_service
      - USER_SERVICE_NAME=user_service
      - GRPC_PORT=50033
      - WEBSOCKET_PORT=50088

  chat-service2:
    build:
      context: ./src/ChatService
    container_name: chat-service2
    ports:
      - "50034:50034"
      - "50089:50089"
    depends_on:
      - service-discovery
      - user-service
      - mongodb
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CHAT_CONNECTION_STRING=${CONNECTION_STRING}
      - CHAT_DATABASE_NAME=${CHAT_DATABASE_NAME}
      - SERVICE_DISCOVERY_ADDRESS=${SERVICE_DISCOVERY_ADDRESS}
      - SERVICE_URL=chat-service2:50034
      - SERVICE_NAME=chat_service
      - USER_SERVICE_NAME=user_service
      - GRPC_PORT=50034
      - WEBSOCKET_PORT=50089

  gateway:
    build:
      context: ./src/Gateway
    container_name: gateway
    ports:
      - "5000:5000"
    depends_on:
      - service-discovery
      - user-service
      - user-service2
      - chat-service
      - redis
      - mongodb
    networks:
      - app-network
    env_file: ./src/Gateway/.env

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data: