version: '3.8'

services:
  service-discovery:
    build:
      context: ./src/ServiceDiscovery
    container_name: service-discovery
    ports:
      - "5003:5003"
    networks:
      - app-network
    env_file: ./src/ServiceDiscovery/.env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db

  user-service:
    build:
      context: ./src/UserService
    container_name: user-service
    ports:
      - "50000:50000"
      - "51000:51000"
    depends_on:
      - redis
      - service-discovery
      - mongodb
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USER_CONNECTION_STRING=${CONNECTION_STRING}
      - USER_DATABASE_NAME=${USER_DATABASE_NAME}
      - SERVICE_DISCOVERY_ADDRESS=${SERVICE_DISCOVERY_ADDRESS}
      - SERVICE_URL=user-service:50000
      - SERVICE_NAME=user_service
      - JWT_SECRET=${JWT_SECRET}
      - GRPC_PORT=50000
      - WEBSOCKET_PORT=51000

  user-service2:
    build:
      context: ./src/UserService
    container_name: user-service2
    ports:
      - "50001:50001"
      - "51001:51001"
    depends_on:
      - redis
      - service-discovery
      - mongodb
      - user-service
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USER_CONNECTION_STRING=${CONNECTION_STRING}
      - USER_DATABASE_NAME=${USER_DATABASE_NAME}
      - SERVICE_DISCOVERY_ADDRESS=${SERVICE_DISCOVERY_ADDRESS}
      - SERVICE_URL=user-service2:50001
      - SERVICE_NAME=user_service
      - JWT_SECRET=${JWT_SECRET}
      - GRPC_PORT=50001
      - WEBSOCKET_PORT=51001

  user-service3:
    build:
      context: ./src/UserService
    container_name: user-service3
    ports:
      - "50002:50002"
      - "51002:51002"
    depends_on:
      - redis
      - service-discovery
      - mongodb
      - user-service2
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USER_CONNECTION_STRING=${CONNECTION_STRING}
      - USER_DATABASE_NAME=${USER_DATABASE_NAME}
      - SERVICE_DISCOVERY_ADDRESS=${SERVICE_DISCOVERY_ADDRESS}
      - SERVICE_URL=user-service3:50002
      - SERVICE_NAME=user_service
      - JWT_SECRET=${JWT_SECRET}
      - GRPC_PORT=50002
      - WEBSOCKET_PORT=51002

  chat-service:
    build:
      context: ./src/ChatService
    container_name: chat-service
    ports:
      - "60000:60000"
      - "61000:61000"
    depends_on:
      - service-discovery
      - user-service
      - mongodb
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CHAT_CONNECTION_STRING=${CONNECTION_STRING}
      - CHAT_DATABASE_NAME=${CHAT_DATABASE_NAME}
      - SERVICE_DISCOVERY_ADDRESS=${SERVICE_DISCOVERY_ADDRESS}
      - SERVICE_URL=chat-service:60000
      - SERVICE_NAME=chat_service
      - USER_SERVICE_NAME=user_service
      - GRPC_PORT=60000
      - WEBSOCKET_PORT=61000

  chat-service2:
    build:
      context: ./src/ChatService
    container_name: chat-service2
    ports:
      - "60001:60001"
      - "61001:61001"
    depends_on:
      - service-discovery
      - user-service
      - chat-service
      - mongodb
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CHAT_CONNECTION_STRING=${CONNECTION_STRING}
      - CHAT_DATABASE_NAME=${CHAT_DATABASE_NAME}
      - SERVICE_DISCOVERY_ADDRESS=${SERVICE_DISCOVERY_ADDRESS}
      - SERVICE_URL=chat-service2:60001
      - SERVICE_NAME=chat_service
      - USER_SERVICE_NAME=user_service
      - GRPC_PORT=60001
      - WEBSOCKET_PORT=61001

  chat-service3:
    build:
      context: ./src/ChatService
    container_name: chat-service3
    ports:
      - "60002:60002"
      - "61002:61002"
    depends_on:
      - service-discovery
      - user-service
      - chat-service2
      - mongodb
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CHAT_CONNECTION_STRING=${CONNECTION_STRING}
      - CHAT_DATABASE_NAME=${CHAT_DATABASE_NAME}
      - SERVICE_DISCOVERY_ADDRESS=${SERVICE_DISCOVERY_ADDRESS}
      - SERVICE_URL=chat-service3:60002
      - SERVICE_NAME=chat_service
      - USER_SERVICE_NAME=user_service
      - GRPC_PORT=60002
      - WEBSOCKET_PORT=61002

  gateway:
    build:
      context: ./src/Gateway
    container_name: gateway
    ports:
      - "5000:5000"
    depends_on:
      - service-discovery
      - user-service
      - user-service2
      - user-service3
      - chat-service
      - chat-service2
      - chat-service3
      - redis
      - mongodb
    networks:
      - app-network
    env_file: ./src/Gateway/.env

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data: