# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import service_registry_pb2 as protos_dot_service__registry__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/service_registry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServiceRegistryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterService = channel.unary_unary(
                '/ServiceRegistry/RegisterService',
                request_serializer=protos_dot_service__registry__pb2.RegisterServiceRequest.SerializeToString,
                response_deserializer=protos_dot_service__registry__pb2.RegisterServiceResponse.FromString,
                _registered_method=True)
        self.DiscoverService = channel.unary_unary(
                '/ServiceRegistry/DiscoverService',
                request_serializer=protos_dot_service__registry__pb2.DiscoverServiceRequest.SerializeToString,
                response_deserializer=protos_dot_service__registry__pb2.DiscoverServiceResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/ServiceRegistry/Heartbeat',
                request_serializer=protos_dot_service__registry__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=protos_dot_service__registry__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class ServiceRegistryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterService': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterService,
                    request_deserializer=protos_dot_service__registry__pb2.RegisterServiceRequest.FromString,
                    response_serializer=protos_dot_service__registry__pb2.RegisterServiceResponse.SerializeToString,
            ),
            'DiscoverService': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverService,
                    request_deserializer=protos_dot_service__registry__pb2.DiscoverServiceRequest.FromString,
                    response_serializer=protos_dot_service__registry__pb2.DiscoverServiceResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=protos_dot_service__registry__pb2.HeartbeatRequest.FromString,
                    response_serializer=protos_dot_service__registry__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ServiceRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ServiceRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceRegistry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServiceRegistry/RegisterService',
            protos_dot_service__registry__pb2.RegisterServiceRequest.SerializeToString,
            protos_dot_service__registry__pb2.RegisterServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscoverService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServiceRegistry/DiscoverService',
            protos_dot_service__registry__pb2.DiscoverServiceRequest.SerializeToString,
            protos_dot_service__registry__pb2.DiscoverServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ServiceRegistry/Heartbeat',
            protos_dot_service__registry__pb2.HeartbeatRequest.SerializeToString,
            protos_dot_service__registry__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
