# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/service_registry.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protos/service_registry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dprotos/service_registry.proto\"C\n\x16RegisterServiceRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x13\n\x0bservice_url\x18\x02 \x01(\t\";\n\x17RegisterServiceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\".\n\x16\x44iscoverServiceRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\"5\n\x17\x44iscoverServiceResponse\x12\x1a\n\x08services\x18\x01 \x03(\x0b\x32\x08.Service\"4\n\x07Service\x12\x13\n\x0bservice_url\x18\x01 \x01(\t\x12\x14\n\x0clast_seen_at\x18\x02 \x01(\t\"\'\n\x10HeartbeatRequest\x12\x13\n\x0bservice_url\x18\x01 \x01(\t\"5\n\x11HeartbeatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd1\x01\n\x0fServiceRegistry\x12\x44\n\x0fRegisterService\x12\x17.RegisterServiceRequest\x1a\x18.RegisterServiceResponse\x12\x44\n\x0f\x44iscoverService\x12\x17.DiscoverServiceRequest\x1a\x18.DiscoverServiceResponse\x12\x32\n\tHeartbeat\x12\x11.HeartbeatRequest\x1a\x12.HeartbeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.service_registry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERSERVICEREQUEST']._serialized_start=33
  _globals['_REGISTERSERVICEREQUEST']._serialized_end=100
  _globals['_REGISTERSERVICERESPONSE']._serialized_start=102
  _globals['_REGISTERSERVICERESPONSE']._serialized_end=161
  _globals['_DISCOVERSERVICEREQUEST']._serialized_start=163
  _globals['_DISCOVERSERVICEREQUEST']._serialized_end=209
  _globals['_DISCOVERSERVICERESPONSE']._serialized_start=211
  _globals['_DISCOVERSERVICERESPONSE']._serialized_end=264
  _globals['_SERVICE']._serialized_start=266
  _globals['_SERVICE']._serialized_end=318
  _globals['_HEARTBEATREQUEST']._serialized_start=320
  _globals['_HEARTBEATREQUEST']._serialized_end=359
  _globals['_HEARTBEATRESPONSE']._serialized_start=361
  _globals['_HEARTBEATRESPONSE']._serialized_end=414
  _globals['_SERVICEREGISTRY']._serialized_start=417
  _globals['_SERVICEREGISTRY']._serialized_end=626
# @@protoc_insertion_point(module_scope)
